package com.example.chen.realtime.dao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.chen.realtime.bean.LiveCategory;
import com.example.chen.realtime.bean.LiveInfo;

import com.example.chen.realtime.dao.greendao.LiveCategoryDao;
import com.example.chen.realtime.dao.greendao.LiveInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig liveCategoryDaoConfig;
    private final DaoConfig liveInfoDaoConfig;

    private final LiveCategoryDao liveCategoryDao;
    private final LiveInfoDao liveInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        liveCategoryDaoConfig = daoConfigMap.get(LiveCategoryDao.class).clone();
        liveCategoryDaoConfig.initIdentityScope(type);

        liveInfoDaoConfig = daoConfigMap.get(LiveInfoDao.class).clone();
        liveInfoDaoConfig.initIdentityScope(type);

        liveCategoryDao = new LiveCategoryDao(liveCategoryDaoConfig, this);
        liveInfoDao = new LiveInfoDao(liveInfoDaoConfig, this);

        registerDao(LiveCategory.class, liveCategoryDao);
        registerDao(LiveInfo.class, liveInfoDao);
    }
    
    public void clear() {
        liveCategoryDaoConfig.clearIdentityScope();
        liveInfoDaoConfig.clearIdentityScope();
    }

    public LiveCategoryDao getLiveCategoryDao() {
        return liveCategoryDao;
    }

    public LiveInfoDao getLiveInfoDao() {
        return liveInfoDao;
    }

}
